name: gaze_web
version: 0.0.1

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  gaze_shared:
    path: ../gaze-shared
  angular2: 2.0.0-beta.0
  browser: ^0.10.0
  websockets: ^0.1.1

transformers:
- angular2:
    entry_points: web/main.dart
