name: gaze_shared
author: Steven Roose <stevenroose@gmail.com>

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  collection: "^1.2.0"
  crypto: "^0.9.1"
  cryptoutils: "^0.2.0"
  events: "^0.1.2"

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
