name: "gaze_backend"
author: Steven Roose <stevenroose@gmail.com>

environment:
  sdk: ">=1.0.0 <2.0.0"

dependencies:
  gaze_shared:
    path: modules/gaze-shared
  args: ">=0.10.0 <0.14.0"
  events: "^0.1.1+1"
  http: "^0.11.3+3"
  logging: "^0.11.2"
  reddit: "^0.3.3"
  shelf: ">=0.6.0 <0.7.0"
  shelf_web_socket: "^0.0.1+4"
  source_gen: any
  zengen: "^0.3.0"
